version: '3'
services:
  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - '3002:3002'
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'